services:
  postgres:
    image: postgres:16
    container_name: fraud-detection-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fraud_detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - fraud_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fraud-detection-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  fraud_postgres_data:
