"""create fraud score table

Revision ID: 3eb90ad307bc
Revises: 
Create Date: 2026-05-09 21:44:31.582239

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3eb90ad307bc'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=150), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('rules_triggered', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('transaction_created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scored_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_fraud_scores_customer_id'), 'fraud_scores', ['customer_id'], unique=False
    )
    op.create_index(
        op.f('ix_fraud_scores_transaction_id'), 'fraud_scores', ['transaction_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_scores_transaction_id'), table_name='fraud_scores')
    op.drop_index(op.f('ix_fraud_scores_customer_id'), table_name='fraud_scores')
    op.drop_table('fraud_scores')
    # ### end Alembic commands ###
